# Libraries To Be Used:
1. Numpy
2. Pandas
3. Matplotlib

In [1]:
# Importing Library
import numpy as np

In [2]:
#Coverting lists to numpy arrays
list = [1,2,3,4,5]
print list
print type(list)
print '-'*20
array = np.asarray(list)
print array
print type(array)
print array.dtype
print array.shape

[1, 2, 3, 4, 5]
<type 'list'>
--------------------
[1 2 3 4 5]
<type 'numpy.ndarray'>
int64
(5,)


In [3]:
#Create new numpy arrays
new_array = np.array([[1,2,3] , [4,5,6]])
print new_array
print new_array.shape

[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
#Create arrays of zeros
arr0 = np.zeros((3,3),dtype = 'int64')
print arr0
print arr0.dtype

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [10]:
#Create identity matrix
I = np.eye(5,5)
print I

#You can apply basic Mathematical operations

print '-'*20
print I*5

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
--------------------
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [20]:
#Create arrays of ones
one = np.ones((5,5))
print one
print '-'*20
#print one*5
print one.dtype

two = np.ones((5,5),'int32')
print two
print two.dtype

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
--------------------
float64
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int32


In [23]:
# Copying the arrays 
arr = two.copy()
print arr
print arr.shape

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(5, 5)


In [36]:
#Reshaping
array = np.array([1,2,3,4,5,6,7,8,9,10])
print array
print array.shape

print 'RESHAPING'
array1 = array.reshape((2,5))
print array1.shape

# -1 means default value
array2 = array.reshape((2,-1))
print array2.shape

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
RESHAPING
(2, 5)
(2, 5)


In [50]:
#Random Numpy Arrays
r_array = np.random.random((5,5))
print r_array
#Value is B/W 0 and 1
#print r_array.mean()

[[0.06327435 0.67478347 0.26368435 0.34569785 0.11016254]
 [0.9811393  0.26015914 0.29292087 0.0501351  0.25519086]
 [0.52829117 0.11124733 0.68917702 0.5541963  0.69112729]
 [0.08054701 0.71039136 0.08477225 0.42614197 0.20287585]
 [0.1101152  0.73029714 0.85430591 0.56176219 0.65868203]]


In [56]:
#You can find mean also
print r_array.mean()
print (one).mean()
print (one*2).mean()

0.41164311384583335
1.0
2.0


In [63]:
#Random Arrays with range of our choice
a = np.random.randint(low = -5 , high = 5 , size = (5,5))
print a

[[-2  4 -1  3  2]
 [ 2 -2  4  3 -3]
 [ 3  4  2 -4  2]
 [ 1 -3  3 -5 -3]
 [-5  0 -1  1 -1]]


In [64]:
#Creating Array with constant fixed value
fix = np.full((5,5) , 1.23)
print fix

[[1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]]


In [69]:
#Creating Array with set sequence
seq = np.arange(-10 , 10 , 2)
print seq

#It does not take the last value   
# Consider it as [ )
last = np.arange(-5 , 5)
print last

[-10  -8  -6  -4  -2   0   2   4   6   8]
[-5 -4 -3 -2 -1  0  1  2  3  4]


In [70]:
# Creating an array equal spaces B/W elements
equal = np.linspace(-1 , 1 , 5)
print equal

[-1.  -0.5  0.   0.5  1. ]


# INDEXING

In [78]:
# In python indexing starts from 0
array = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print array
print array.shape

print '-'*20

print array[0,0] , '\n' , array[2,2]

# -1 means the last value
print array[-1,-1]

#We can change the value of the particular index too
array[0,0] = 9
print array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
--------------------
1 
9
9
[[9 2 3]
 [4 5 6]
 [7 8 9]]


In [92]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print a

print '-'*20

print a[:5]
#Means from start to end -1 position

print a[2:4]

print a[:5:2]
#Taking every 2nd element

#Reversing
#Space means default value 
print a[-1: :-1]

[ 1  2  3  4  5  6  7  8  9 10]
--------------------
[1 2 3 4 5]
[3 4]
[1 3 5]
[10  9  8  7  6  5  4  3  2  1]


# Array Math

In [112]:
x = np.array([1,2,3])
y = np.array([4,5,6])

# Addition
print x + y
print np.add(x , y)
#Element wise

#Subtraction
print x - y
print np.subtract(x , y)

#Multiplication
print x * y
print np.multiply(x , y)

#Division
#For proper results we should use float
# so
a = np.array([1,2,3] , 'float64')
b = np.array([4,5,6] , 'float64')
print a/b
print np.divide(a , b)

#Squareroot
print np.sqrt(a)

print np.exp(a)

[5 7 9]
[5 7 9]
[-3 -3 -3]
[-3 -3 -3]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [115]:
#Did u notice that we didn't do matrix multipliacation we just did element-wise multipliaction
#That's how we do matrix multiplication

print a.dot(b)
print np.dot(a , b)


print x.dot(y)
print np.dot(x , y)

32.0
32.0
32
32


In [125]:
#Computations on array
print np.sum(x)
print np.average(x)


new = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print new
print np.sum(new , axis=0)#Sum along each column
print np.sum(new , axis=1)#sum along each row

6
2.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [132]:
#Transpose

print new
print 'TRANSPOSE'
print new.T


#What if we do the transpose of rank=1 matrix
mat = np.random.randint(5,10, size = 5)
print mat
print mat.shape
print mat.T
print mat.T.shape
#NO change

[[1 2 3]
 [4 5 6]
 [7 8 9]]
TRANSPOSE
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[7 9 9 7 7]
(5,)
[7 9 9 7 7]
(5,)
